### ISSUE TITLE
Choose PDF(file) only shows pictures in media Library

### ISSUE THREAD

**Issue by sirtheta** [kazbekkadalashvili/elementor-pdf-viewer#1]
When I want to choose a PDF from my media Library, I can only choose from Pictures. I can't see any PDF in my library although I know they are there...

**Comment by kazbekkadalashvili** [comment]
@sirtheta  Yes, I know about that. I will try to fix this in the next updates. Thanks for bag report

**Comment by PaulProe** [comment]
are you aware of this project: [(https://github.com/CaerCam/media-link-for-elementor)]  Works with current version of Elementor. Maybe some ideas that would work with your plugin and solve the pdf display issue?

**Comment by kazbekkadalashvili** [comment]
@sirtheta @PaulProe I released updates on wordpress.org ( https://wordpress.org/plugins/pdf-viewer-for-elementor/ ). Can you update the plugin and let me know if this works for you? Thank

Best,
Kaz

**Comment by sirtheta** [comment]
Works perfect now. Thanks for your work!
