### ISSUE TITLE
pdf not loading

### ISSUE THREAD

**Issue by Ronnisgithub** [kazbekkadalashvili/elementor-pdf-viewer#2]
Sometimes pdf-files are not loaded without any error-code. In this case the content is empty.
Do you know this problem?

**Comment by kazbekkadalashvili** [comment]
@Ronnisgithub  No. Thanks for the bug report. In the near future, I will try to release a big update and try to fix this bug too. Can you describe the problem in more detail? What error is displayed, etc.?

**Comment by Ronnisgithub** [comment]
No error is displayed, here is the adress to try with several browsers:
[staging.nunu.at](https://staging.nunu.at/)
In the top-navigation choose _Hefte_ and try one or several issues, f.i _1/2019_ or another
Thanx!

**Comment by Ronnisgithub** [comment]
Hi, please let me know if i have a chance to get a bug fix in the next days, because this site has to go online asap. 
Thank you for your feedback,
regards
Ronni

**Comment by kazbekkadalashvili** [comment]
Hi Ronni

Can you try installing the plugin using wordpress.org?

https://wordpress.org/plugins/pdf-viewer-for-elementor/

In the latest version of the plugin, I developed another PDFjs element.

If you work with PDF files located on your server, this is the best way to solve problems.

Let me know if I can help you with anything else.

Best,
Kazbek

**Comment by Ronnisgithub** [comment]
Ok, i uploaded this update. But if i try to load files into pdf_embedderJS of elementor the pdf files are not shown in the media library and there is no way to insert a link instead.
That is a problem, that is just mentioned in github discussion.
Nevertheless the links are now working better as before but not really reliable.
Please try out if you have time.

Thank you for your patience!
Regards
Ronni

**Comment by kazbekkadalashvili** [comment]
@Ronnisgithub I released updates on wordpress.org. Can you update the plugin and let me know if this works for you? Thank

Best,
Kaz

**Comment by Ronnisgithub** [comment]
ok, now i can choose pdf from the library.
Thanks a lot!

Regards Ronni

**Comment by kazbekkadalashvili** [comment]
@Ronnisgithub Cool. Happy to help
